In [1]:
import os
import json
from PIL import Image
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [3]:
file_path = '/content/gdrive/MyDrive/ECE1786_project/data1-50.csv'
df_1_50 = pd.read_csv(file_path, header=None, names=['price', 'label', 'link'])

In [4]:
df_1_50['img_dir'] = [i for i in range(1, 51)]

In [5]:
df_1_50.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   price    50 non-null     float64
 1   label    50 non-null     object
 2   link     50 non-null     object
 3   img_dir  50 non-null     int64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.7+ KB

In [6]:
df_1_50.head(5)

,price,label,link,img_dir
0,129.99,"Color: white / L: 39.4 - W: 18.9 - H: 30.5, in...",https://www.amazon.ca/Rolanstar-Computer-Outle...,1
1,169.99,"Color: white / L: 55.1 - W: 18.9 - H: 30.5, in...",https://www.amazon.ca/Rolanstar-Computer-Outle...,2
2,149.99,"Color: white / L: 47.2 - W: 18.9 - H: 30.5, in...",https://www.amazon.ca/Rolanstar-Computer-Outle...,3
3,199.99,"Color: white / L: 63.0 - W: 18.5 - H: 30.7, in...",https://www.amazon.ca/Rolanstar-Computer-Drawe...,4
4,299.87,"Color: maple / L: 55.0 - W: 28.0 - H: 28.0, in...",https://www.amazon.ca/SHW-55-Inch-Electric-Adj...,5

In [7]:
file_path = '/content/gdrive/MyDrive/ECE1786_project/officetable51-100.xlsx'
df_51_100 = pd.read_excel(file_path)

In [8]:
df_51_100.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   img_dir  50 non-null     int64
 1   price    50 non-null     float64
 2   label    50 non-null     object
 3   link     37 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 1.7+ KB

In [16]:
df_51_100.head(5)

,img_dir,price,label,link
0,51,169.87,"Color: black / L: 55 - W: 23.8 - H: 28, inch ...",https://www.amazon.ca/SHW-Commercial-Grade-Com...
1,52,239.99,"Color: brown / L: 55 - W: 24 - H: 28.3, inch ...",https://www.amazon.ca/CubiCubi-Standing-Electr...
2,53,149.99,"Color: black / L: 47.2 - W: 18.5 - H: 30, inc...",https://www.amazon.ca/Seventable-Computer-Outl...
3,54,88.97,"Color: black / L: 40 - W: 19 - H: 28, inch / ...",https://www.amazon.ca/SHW-Office-40-Inch-Compu...
4,55,122.87,"Color: black / L: 48 - W: 23.8 - H: 28, inch ...",https://www.amazon.ca/SHW-Office-48-Inch-Compu...

In [9]:
file_path = '/content/gdrive/MyDrive/ECE1786_project/Data.xlsx'
df_101_150 = pd.read_excel(file_path)

In [10]:
df_101_150.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   img_dir  50 non-null     int64
 1   price    50 non-null     float64
 2   label    50 non-null     object
dtypes: float64(1), int64(1), object(1)
memory usage: 1.3+ KB

In [11]:
df_101_150.head()

   img_dir    price                                              label
0      101   269.99  Color: black / L: 63 - W: 32 - H: 30, inch / P...
1      102   269.99  Color: grey / L: 63 - W: 32 - H: 30, inch / Pr...
2      103   269.99  Color: oak / L: 63 - W: 32 - H: 30, inch / Pri...
3      104  1699.00  Color: black / L: 70.87 - W: 35.43 - H: 29.53,...
4      105  1499.00  Color: white / L: 62.99 - W: 35.43 - H: 29.53,...

In [12]:
file_path = '/content/gdrive/MyDrive/ECE1786_project/diningtables150-200.csv'
df_151_200 = pd.read_csv(file_path)

In [19]:
df_151_200.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   img_dir  50 non-null     int64
 1   price    50 non-null     float64
 2   label    50 non-null     object
dtypes: float64(1), int64(1), object(1)
memory usage: 1.3+ KB

In [13]:
combined_df = pd.concat([
    df_1_50[['img_dir', 'price', 'label']],
    df_51_100[['img_dir', 'price', 'label']],
    df_101_150[['img_dir', 'price', 'label']],
    df_151_200[['img_dir', 'price', 'label']]
])

In [14]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 0 to 49
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   img_dir  200 non-null    int64
 1   price    200 non-null    float64
 2   label    200 non-null    object
dtypes: float64(1), int64(1), object(1)
memory usage: 6.2+ KB

In [15]:
output_path = "/content/gdrive/MyDrive/ECE1786_project/product_data_full.csv"
combined_df.to_csv(output_path, index=False)